# Generated by Django 2.0.5 on 2018-06-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180604_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_mark_maintenance', 'Set book as maintenance'), ('can_renew', 'Renew a book'))},
        ),
    ]
