# Generated by Django 2.0.5 on 2018-06-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180604_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_create_author', 'Create author'), ('can_change_author', 'Change author'), ('can_delete_author', 'Delete author'))},
        ),
    ]
