# Generated by Django 2.0.5 on 2018-06-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180604_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_create_book', 'Create book'), ('can_change_book', 'Change book'), ('can_delete_book', 'Delete book'))},
        ),
    ]
